import Navbar from './navbar';
import Footer from './footer'
import Head from 'next/head'

export default function Layout ({ children }) {
  return (
    <div>
      <Head>
        <title>Vacation Helper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
        <main>{children}</main>
      <Footer />
    </div>
  );
}